numero =10
numero +=10
numero +=1

nombre="bienvenido"
brandon= "hola "+nombre+" brandon"

print(brandon)
print(numero)

#vamos a ver como convertir  un boleano o int a texto

condicion="juanito"
condicion2=f"hola {condicion} como estas"
del condicion
print("resultado:"+condicion2)


#para borrar el nombre o condicion vamos a usar el parametro del

puca =True
trozo = f"hola {puca} como estas"
del puca

print("resultado2:",trozo)


#operador in ,and , not in
pucaa =True
trozoo = f"hola {pucaa} como estas"
del pucaa
print("hola" in trozoo ) # si te sale true es porque el comentario  que hizo esta en la variable trozoo
print("hola" not in  trozoo )#si te sale false es porque  pusimos not in ,para que no salga false debemos de poner en el comentario algo que no este en el codigo


